Baca data

In [16]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
import bisect
import numpy as np

with open('CensusIncome.names.txt', 'r') as fname:
    sname = fname.read()
names=np.array(sname[sname.find("age"):].split(".\n"))
#print(names)

#Encode Data Workclass
workclass = preprocessing.LabelEncoder()
workclass.fit(np.array(names[1][names[1].find(":")+2:].split(", ")))
#Handle Unknown Data : '?'
le_classes = workclass.classes_.tolist()
bisect.insort_left(le_classes, '?')
workclass.classes_ = le_classes
#print(workclass.classes_)

#Encode Data Education
education = preprocessing.LabelEncoder()
education.fit(np.array(names[3][names[3].find(":")+2:].split(", ")))
le_classes = education.classes_.tolist()
bisect.insort_left(le_classes, '?')
education.classes_ = le_classes
#print(education.classes_)

marital_status = preprocessing.LabelEncoder()
marital_status.fit(np.array(names[5][names[5].find(":")+2:].split(", ")))
le_classes = marital_status.classes_.tolist()
bisect.insort_left(le_classes, '?')
marital_status.classes_ = le_classes
#print(marital_status.classes_)

occupation = preprocessing.LabelEncoder()
occupation.fit(np.array(names[6][names[6].find(":")+2:].split(", ")))
le_classes = occupation.classes_.tolist()
bisect.insort_left(le_classes, '?')
occupation.classes_ = le_classes
#print(occupation.classes_)

relationship = preprocessing.LabelEncoder()
relationship.fit(np.array(names[7][names[7].find(":")+2:].split(", ")))
le_classes = relationship.classes_.tolist()
bisect.insort_left(le_classes, '?')
relationship.classes_ = le_classes
#print(relationship.classes_)

race = preprocessing.LabelEncoder()
race.fit(np.array(names[8][names[8].find(":")+2:].split(", ")))
le_classes = race.classes_.tolist()
bisect.insort_left(le_classes, '?')
race.classes_ = le_classes
#print(race.classes_)

sex = preprocessing.LabelEncoder()
sex.fit(np.array(names[9][names[9].find(":")+2:].split(", ")))
le_classes = sex.classes_.tolist()
bisect.insort_left(le_classes, '?')
sex.classes_ = le_classes
#print(sex.classes_)

native_country = preprocessing.LabelEncoder()
native_country.fit(np.array(names[13][names[13].find(":")+2:].split(", ")))
le_classes = native_country.classes_.tolist()
bisect.insort_left(le_classes, '?')
native_country.classes_ = le_classes
#print(native_country.classes_)

#Open Data Cencus
with open('CencusIncome.data.txt', 'r') as fdata:
    s = fdata.read()

raw = s.split("\n")
A = []
print(raw[32560])
length = 32560
for i in range(length):
    A.append(raw[i].split(", "))
    
#Mapping from raw data to  
data_length = 14
cencus_data = []
cencus_target = []
for i in range(length):
    temp = []
    for j in range(data_length):
        if j == 7:
            temp.append(relationship.transform([A[i][j]])[0])
        elif j == 1:
            temp.append(workclass.transform([A[i][j]])[0])
        elif j == 3:
            temp.append(education.transform([A[i][j]])[0])
        elif j == 5:
            temp.append(marital_status.transform([A[i][j]])[0])
        elif j == 6:
            temp.append(occupation.transform([A[i][j]])[0])
        elif j == 8:
            temp.append(race.transform([A[i][j]])[0])
        elif j == 9:
            temp.append(sex.transform([A[i][j]])[0]) 
        elif j == 13:
            temp.append(native_country.transform([A[i][j]])[0])
        else:
            temp.append(int(A[i][j]))
    cencus_data.append(temp)
    cencus_target.append(A[i][data_length])

#Encode Target
target = preprocessing.LabelEncoder()
target.fit(cencus_target)

#Ready to Use Data
y = target.transform(cencus_target)    
X = np.array(cencus_data)


52, Self-emp-inc, 287927, HS-grad, 9, Married-civ-spouse, Exec-managerial, Wife, White, Female, 15024, 0, 40, United-States, >50K


In [17]:
# GAUSSIAN NAIVE BAYES #
from sklearn.naive_bayes import GaussianNB
from time import time
import pandas as pd
from sklearn import metrics
from sklearn.metrics import accuracy_score
#newer vers: from sklearn.model_selection import KFold
#older vers: from sklearn.cross_validation import StratifiedKFold 
from sklearn.model_selection import KFold

#older vers: kf = StratifiedKFold(y, n_folds=10, shuffle=True)
#newer vers: kf = KFold(n_splits=10, shuffle=True)
kf = KFold(n_splits=10, shuffle=True)

table = []
i = 1
for train, test in kf.split(X,y):
    x_train = [X[i] for i in train]
    y_train = [y[i] for i in train]
    x_test = [X[i] for i in test]
    y_test = [y[i] for i in test]
    
    ts = time()
    model = GaussianNB().fit(x_train, y_train)
    trainingtime = time() - ts
    
    ts = time()
    prediction = model.predict(x_test)
    predictiontime = time() - ts
    
    score = accuracy_score(prediction, y_test)
    
    print(i)
    i += 1
    print(metrics.confusion_matrix(y_test,prediction))
    
    table += [[score, trainingtime, predictiontime]]
    
print()
print(pd.DataFrame(table, columns=['score', 'training time', 'prediction time'], index=range(1,len(table)+1)))

1
[[2305  124]
 [ 593  234]]
2
[[2369  124]
 [ 511  252]]
3
[[2339  145]
 [ 537  235]]
4
[[2337  128]
 [ 543  248]]
5
[[2328  141]
 [ 551  236]]
6
[[2374  104]
 [ 530  248]]
7
[[2352  131]
 [ 510  263]]
8
[[2371  112]
 [ 517  256]]
9
[[2334  125]
 [ 555  242]]
10
[[2340  137]
 [ 554  225]]

       score  training time  prediction time
1   0.779791       0.145091         0.015009
2   0.804975       0.169623         0.012008
3   0.790541       0.168611         0.018017
4   0.793919       0.167112         0.015015
5   0.787469       0.163547         0.013597
6   0.805283       0.165122         0.010538
7   0.803133       0.139069         0.012515
8   0.806818       0.140533         0.012000
9   0.791155       0.145573         0.011998
10  0.787776       0.137597         0.015989


The nltk version is 3.2.2.
The scikit-learn version is 0.18.1.
